### ISSUE TITLE
valkkafs conversion example

### ISSUE THREAD

**Issue by scipioni** [elsampsa/valkka-examples#3] opened 2019-06-14 14:07 UTC
Please can you post an example about reading valkkafs and convert it with FileFrameFilter or
publish it with RTSPServer ?

Great project ;-)

**Comment by eranpet** [comment] 2019-06-18 16:05
Pushing livestream to RTSP server should be done like this:
```
ValkkaFSReaderThread --> FileCacherThread --> filterchain --> LiveThread
```
The valkkafsreaderthread pushes one block at a time down the filterchain.  The frames must then be cached in filecacherthread.  Then filecacherthread can be given some commands to  pass the frames at "play-speed" down the filterchain.

It seems that filecacherthread is not documented at this moment..  here are some misc. notes on the subject: https://elsampsa.github.io/valkka-core/html/filesystem.html

You can also adventure to ```test_studio_5.py``` and follow the code there.

I guess ValkkaFSReaderThread can push directly to FileFrameFilter, right @elsampsa ?

There should be some examples on these things in the near future.

**Comment by elsampsa** [comment] 2019-06-25 07:43
We do have a problem here ..

libValkka uses "SetupFrames".  These are sent by the thread that provides the frames (like LiveThread).  They are used to mark the start of the stream and for example, to initialize the decoders. 

FileFrameFilter uses SetupFrames to initialize the muxer: if there are no SetupFrames, nothing happens.
The problem is, that ValkkaFSReaderThread does *not* send SetupFrames .. that's done by the FileCacherThread.  Not sure if it's a good design decision..  

We could always do this: ```ValkkaFSReaderThread --> FileCacherThread --> FileFrameFilter```.  Or could change ValkkaFSReaderThread so that it sends SetupFrames.  I'm starting to like the latter option more.  Not sure though.

**Comment by elsampsa** [comment] 2019-06-25 08:21
ok .. I finally got my head around this.  We're doing it ok.  ValkkaFSReaderThread should be as dummy as possible and stateless (no notion of stream start). It just knows how to send blocks of frames, so no SetupFrames from there.

Sending SetupFrames must be done outside of ValkkaFSReaderThread (for example, using FileCacherThread).

Instead of this:
```ValkkaFSReaderThread --> FileCacherThread --> FileFrameFilter```

We could do this:
```ValkkaFSReaderThread --> InitStreamFilter --> FileFrameFilter```

Where ```InitStreamFilter``` adds SetupFrames to the stream.

@eranpet : you know what to do.  :)  (like, you know, implementing a new FrameFilter)

**Comment by eranpet** [comment] 2019-07-26 08:39
.. when the 0.13.1 is ready: https://launchpad.net/~sampsa-riikonen/+archive/ubuntu/valkka/+packages
.. try this:
https://elsampsa.github.io/valkka-examples/_build/html/lesson_11.html#matroska-export

**Comment by elsampsa** [comment] 2020-11-11 13:45
closing for the moment

**Closed as completed by elsampsa** 2020-11-11 13:45 UTC
